const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('pty', {
  spawn: (id, cols, rows, cwd, cmd) => ipcRenderer.invoke('pty:spawn', { id, cols, rows, cwd, cmd }),
  nextId: () => ipcRenderer.sendSync('tab:next-id'),
  wcId: () => ipcRenderer.sendSync('wc:id'),
  moveTab: (m) => ipcRenderer.send('tab:move', m),
  pullTab: (id, srcWc) => ipcRenderer.send('tab:pull', { id, srcWc }),
  tabToNewWindow: (id) => ipcRenderer.send('tab:to-new-window', { id }),
  closeWindow: () => ipcRenderer.send('window:close'),
  onAdopt: (cb) => ipcRenderer.on('tab:adopt', (e, m) => cb(m)),
  onSendTab: (cb) => ipcRenderer.on('tab:send', (e, m) => cb(m.id, m.targetWc)),
  onSendAll: (cb) => ipcRenderer.on('tabs:send-all', (e, m) => cb(m.targetWc)),
  pathFor: (file) => webUtils.getPathForFile(file),
  projects: () => ipcRenderer.invoke('projects:list'),
  write: (id, data) => ipcRenderer.send('pty:write', { id, data }),
  resize: (id, cols, rows) => ipcRenderer.send('pty:resize', { id, cols, rows }),
  kill: (id) => ipcRenderer.send('pty:kill', { id }),
  onData: (cb) => ipcRenderer.on('pty:data', (e, m) => cb(m.id, m.data)),
  onExit: (cb) => ipcRenderer.on('pty:exit', (e, m) => cb(m.id)),
  ready: () => ipcRenderer.send('renderer:ready'),
  onRestore: (cb) => ipcRenderer.once('session:restore', (e, s) => cb(s)),
  saveTabs: (meta) => ipcRenderer.send('session:tabs', meta),
  onOpen: (cb) => ipcRenderer.on('open:request', (e, req) => cb(req)),
  onMenu: (cb) => { for (const k of ['new-tab', 'close-tab', 'set-default', 'install-hooks', 'toggle-sidebar', 'tab-to-new-window']) ipcRenderer.on('menu:' + k, () => cb(k)); },
  setDefault: () => ipcRenderer.invoke('default:set'),
  hooksStatus: () => ipcRenderer.invoke('hooks:status'),
  installHooks: () => ipcRenderer.invoke('hooks:install'),
  onAttention: (cb) => ipcRenderer.on('attention', (e, m) => cb(m.id, m.type)),
  onWorking: (cb) => ipcRenderer.on('working', (e, m) => cb(m.id, m.on)),
  contextList: (scope, tabId) => ipcRenderer.invoke('context:list', { scope, tabId }),
  contextOpen: (p) => ipcRenderer.invoke('context:open', p),
  chime: () => ipcRenderer.send('chime'),
});
